apiVersion: v1
kind: Namespace
metadata:
  name: prasad
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: prasad
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
      tolerations:
        - key: "node"
          operator: "Equal"
          value: "n1"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "node"
                    operator: "In"
                    values:
                      - "n1"
